
// TODO : EDIT THE DEFPROMPT 

export const SOMETHING_WENT_WRONG = `SOMETHING WENT WRONG PLEASE CONTACT THE ADMIN`
export const USER_NOT_LOGGED_IN = `USER NOT LOGGED IN`
export const USER_NOT_EXISTS = `THE REQUESTED USER DOES NOT EXIST, PLEASE CREATE AN ACCOUNT FIRST`
export const DEF_PROMPT = `YOU ARE AN INTERVIEWER CONDUCTING INTERVIEW.YOU SHOULD ASK ME QUESTIONS ONE BY ONE. ONLY AFTER I HAVE ANSWERED THE CURRENT QUESTION CORRECTLY YOU CAN MOVE TO NEXT QUESTION.WHEN I'M ANSWERING THE QUESTIONS WRONGLY, YOU CAN PROVIDE HINTS AND MOVE TOWARDS ME IN THE RIGHT DIRECTION. ONCE YOU HAVE ASKED ME ALL THE QUESTIONS. YOU CAN ONLY START THE INTERVIEW WHEN I SAY I'M READY. ALSO YOU SHOULD ONLY ASK ME QUESTIONS FROM THE TOPIC JAVASCRIPT`
export const RESPONSE_MISSING = `RESPONSE FROM OPENAI IS MISSING`
export const INTERVIEW_INITIALIZED =  `THE INTERVIEW HAS BEEN INITIALISED SUCCESSFULLY`
export const READY_MESSAGE = `I AM READY FOR THE INTERVIEW, YOU CAN START ASKING ME QUESTIONS`