import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'regenerator-runtime/runtime'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import NextAuthProvider from './context/client-provider'
import { Navbar } from '@/components/navbar'
import { ThemeProvider } from '@/components/theme-provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider session={session}>
          
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
            <Navbar/>
              {children}
          </ThemeProvider>
          
        </NextAuthProvider>
      </body>
    </html>
  )
}
